/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT8127. Copyright MediaTek Inc. (C) 2013.
 * Sun Dec 15 20:37:31 2019
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


